version: '3'
services:
    fiitapixel-app:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - DB_NAME=${DB_DATABASE}
          - DB_USER=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
