version: '3'
services:
    fiitapixel-postgres:
      image: 'postgres:latest'
      container_name: fiitapixel-postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
      volumes:
        - "./fiitapixel/postgres:/var/lib/postgresql/data"
      networks:
        - fiitapixel-network

    fiitapixel-app:
      image: 'fiitapixel:latest'
      container_name: fiitapixel-app
      ports:
        - "80:80"
      volumes:
        - "./fiitapixel/storage:/var/www/storage"
        - "./fiitapixel/nginx.conf:/etc/nginx/sites-enabled/default"
      command: sudo /etc/init.d/nginx reload && sudo /etc/init.d/nginx restart
      networks:
        - fiitapixel-network
      depends_on:
        - fiitapixel-postgres

networks:
  fiitapixel-network:
    driver: bridge
